dataset: "SimpleStories-Both"
tokenizer: "o200k_base"
path:
  log_dir: "logs/simple_stories"
model:
  d_model: 512
  n_heads: 8
  n_layers: 6

train:
  manual_seed: 1234
  epochs: 100
  batch_size: 16
  learning_rate: 0.001
  betas: [0.9, 0.95]
  weight_decay: 0.0001
  lr_decay: 0.99
  save_epochs: 10
  validation_epochs: 10
  logging_steps: 100